#!/bin/zsh

RED='\e[31m'
GREEN='\e[32m'
YELLOW='\e[33m'
BLUE='\e[34m'
RESET='\e[0m'

if [ -n "$BASH_VERSION" ]; then
    echo "This script is running in Bash, which is not supported"
    exit 1
elif [ -n "$ZSH_VERSION" ]; then
    echo "This script is running in Zsh."
else
    echo "This script is running in an unknown shell."
    exit 1
fi

build/timestamp.sh
if [ $? -eq 0 ]; then
    echo -e "${GREEN}Timestamp set${RESET}"
else
    echo -e "${YELLOW}Warning - Timestamp insertion failed$. Continuing...{RESET}"
fi

build/wordcount.sh book.epub
if [ $? -eq 0 ]; then
    echo -e "${GREEN}Wordcount set${RESET}"
else
    echo -e "${YELLOW}Appending word count insertion failed. Continuing...${RESET}"
fi

rm -f book.epub
cd book
zip -q0X "../book.epub" mimetype
zip -qXr9D "../book.epub" * -x "*.git*" -x "*.DS_Store"

echo -e "${GREEN}ePub generated OK${RESET}"

cd ..
java_path="$(ls -d bin/Java/jdk*)/Contents/Home/bin/java"
echo "Using Java at path: $java_path"
"$java_path" --version

if [[ $1 = "-c" ]]; then
    "$java_path" -jar bin/epubcheck-5.2.1/epubcheck.jar book.epub
else
    echo -e "${YELLOW}Skipping ePub check...${RESET}"
fi

echo -e "${GREEN}Script complete${RESET}"

